/*
 * This source file was generated by the Gradle 'init' task
 */
package pa11;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class HashSetTest {

    @Test void EmptySet() {
        HashSet set = new HashSet();
        assertEquals(set.size(), 0);
    }
}
